### ISSUE TITLE
1.1.0 Release for 1.18 crashes 1.18.1 server launch

### ISSUE THREAD

**Issue by CanINotUseTruth** [CodedSakura/FabricNoMobGrief#4]
The title mainly says it but from the server console, the 1.1.0 release is incompatible with the 1.18.1 version of fabric.

**Comment by CodedSakura** [comment]
just checked and cannot reproduce it. could you please provide the crashlog?

**Comment by CanINotUseTruth** [comment]
I apologize it seems one of my other admins removed the fabric api which is necessary... I only just got time to look into it more thoroughly.
